resume:
pretrain: ./checkpoints/arid/2022_11_03_06_05_00/model_best.pt
seed: 42
data:
  dataset: arid
  type: frames
  num_segments: 32
  seg_length: 8
  batch_size: 32
  val_batch_size: 16
  worker: 10
  num_classes: 11
  image_tmpl: '{:06d}.jpg'
  train_list: /home/shua0003/arid/train_.txt
  val_list: /home/shua0003/arid/validate_.txt
  label_list: /home/shua0003/arid/mapping_table.txt
  index_bias: 1
  input_size: 224
network:
  arch: ViT-B/16
  motion:
    train: True
    thres: 2.0
    num_layers: 6
    init: False
    lr: 2.e-7
  visual:
    train: False
    lr: 1.e-8
  fusion:
    type: 'transf' # transf or mlp or mean
    train: True
    lr: 1.e-8
  other:
    alpha: 0.1 # deprecated
    train: True
    lr: 1.e-7
  text:
    train: False
optim:
  distributed: True
  amp: True
  type: cosine
  epochs: 100
  start_epoch: 0
  epoch_offset: 0
  optim: adamw
  lr: 1.e-7
  # f_ratio: 0.02
  lr_warmup_step: 20
  momentum: 0.9
  weight_decay: 0.01
  lr_decay_step: 15
  lr_decay_factor: 0.1
  clip_gradient: 20
  grad_accu: 1
logging:
  write_freq: 24
  eval_freq: 1
  save_freq: 2
  chpt_dir: ./checkpoints
