resume:
pretrain: /mnt/e/vit-b-16-8f.pt
seed: 114514
data:
  dataset: hmdb_51
  type: video # video dataset or frames dataset
  num_segments: 40
  seg_length: 8
  batch_size: 24
  val_batch_size: 8
  worker: 4
  num_classes: 51
  image_tmpl: '{:06d}.jpg'
  train_list: /home/neoncloud/hmdb_full/train_lite.txt
  val_list: /home/neoncloud/hmdb_full/validate_lite.txt
  label_list: /home/neoncloud/hmdb_full/mapping_table.txt
  index_bias: 1
  input_size: 224
network:
  arch: ViT-B/16
  motion:
    thres: 2.0
    num_layers: 6
    init: True
  visual:
    train: False
  alpha:
    value: 0.1
    train: False
  text:
    train: False
optim:
  distributed: False
  amp: True
  type: cosine
  epochs: 100
  start_epoch: 0
  epoch_offset: 0
  optim: adamw
  lr: 5.e-7
  f_ratio: 0.02
  lr_warmup_step: 5
  momentum: 0.9
  weight_decay: 0.01
  lr_decay_step: 15
  lr_decay_factor: 0.1
  clip_gradient: 20
  grad_accu: 2
logging:
  write_freq: 6400
  eval_freq: 1
  save_freq: 2
  chpt_dir: ./checkpoints