resume:
pretrain: /home/neoncloud/low_light/checkpoints/ViT-B/16/hmdb/2022_10_31_00_00_26/model_best.pt
seed: 114514
data:
  dataset: low_light
  type: frames
  num_segments: 40
  seg_length: 8
  batch_size: 24
  val_batch_size: 8
  worker: 4
  num_classes: 10
  image_tmpl: '{:06d}.jpg'
  train_list: /home/neoncloud/low_light_video/train_.txt
  val_list: /home/neoncloud/low_light_video/validate_.txt
  label_list: /home/neoncloud/low_light_video/mapping_table.txt
  index_bias: 1
  input_size: 224
network:
  arch: ViT-B/16
  motion:
    train: True
    thres: 4.0
    num_layers: 4
    init: False
    lr: 1.e-8
  visual:
    train: False
    lr: 1.e-7
  fusion:
    type: 'transf' # transf or mlp or mean
    train: True
    lr: 1.e-8
  other:
    alpha: 0.1 # deprecated
    train: False
    lr: 1.e-8
  text:
    train: False
optim:
  distributed: False
  amp: True
  type: cosine
  epochs: 100
  start_epoch: 0
  epoch_offset: 0
  optim: adamw
  lr: 1.e-7
  # f_ratio: 0.02
  lr_warmup_step: 50
  momentum: 0.9
  weight_decay: 0.01
  lr_decay_step: 15
  lr_decay_factor: 0.1
  clip_gradient: 20
  grad_accu: 2
logging:
  write_freq: 6400
  eval_freq: 1
  save_freq: 2
  chpt_dir: ./checkpoints