resume:
pretrain: /mnt/e/vit-b-16-8f.pt
seed: 114514
data:
  dataset: low_light
  num_segments: 32
  seg_length: 8
  batch_size: 4
  worker: 8
  num_classes: 10
  image_tmpl: '{:06d}.jpg'
  train_list: /home/neoncloud/low_light_video/train_.txt
  val_list: /home/neoncloud/low_light_video/validate_.txt
  label_list: /home/neoncloud/low_light_video/mapping_table.txt
  index_bias: 1
  input_size: 224
network:
  arch: ViT-B/16
  motion:
    thres: 4.0
    num_layers: 4
    init: True
  visual:
    train: False
  text:
    train: False
optim:
  amp: True
  type: cosine
  epochs: 50
  start_epoch: 0
  epoch_offset: 0
  optim: adamw
  lr: 5.e-6
  lr_warmup_step: 5
  momentum: 0.9
  weight_decay: 0.2
  lr_decay_step: 15
  lr_decay_factor: 0.1
  clip_gradient: 20
logging:
  print_freq: 5
  eval_freq: 10
  save_freq: 20
  chpt_dir: ./checkpoints